_wandb:
    value:
        cli_version: 0.24.0
        e:
            02ivrsg817qm0iq0epdphdkvh7gpmm4u:
                args:
                    - --batch_size
                    - "128"
                    - --num_epochs
                    - "1000"
                    - --lr
                    - "1e-4"
                    - --kl_weight
                    - "1e-5"
                    - --eval_every
                    - "50"
                    - --failure_threshold
                    - "1000"
                    - --train_scenes
                    - "500"
                    - --val_scenes
                    - "50"
                    - --use_wandb
                    - --wandb_project
                    - Can3Tok-SceneSplat
                    - --wandb_entity
                    - 3D-SSC
                codePath: gs_can3tok_1.py
                codePathLocal: gs_can3tok_1.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "405460807680"
                        used: "6225555456"
                email: hafeez.khan@student.uva.nl
                executable: /home/yli11/.conda/envs/can3tok/bin/python
                git:
                    commit: 3d87fc63f29eeaf92a35cb824310c18d199f90b7
                    remote: https://github.com/Hafeezmhk7/Can3Tok.git
                gpu: NVIDIA H100
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100
                      uuid: GPU-ad7ad994-1388-cdc6-d0ef-aff84321b697
                host: gcn113.local.snellius.surf.nl
                memory:
                    total: "811317764096"
                os: Linux-5.14.0-570.76.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /gpfs/work3/0/prjs1291/Hafeez_thesis/Can3Tok/gs_can3tok_1.py
                python: CPython 3.11.14
                root: /gpfs/work3/0/prjs1291/Hafeez_thesis/Can3Tok
                slurm:
                    cluster_name: snellius
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "9"
                    eclibr: "0"
                    ecplug: "1"
                    erlast: sbatch
                    ersbac: "1"
                    export_env: ALL
                    get_user_env: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: gusei16254
                    job_cpus_per_node: "16"
                    job_end_time: "1769765111"
                    job_gid: "75272"
                    job_gpus: "0"
                    job_id: "18913744"
                    job_name: can3tok_val
                    job_nodelist: gcn113
                    job_num_nodes: "1"
                    job_partition: gpu_h100
                    job_qos: normal
                    job_start_time: "1769693110"
                    job_uid: "75812"
                    job_user: yli11
                    jobid: "18913744"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gcn113
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    step_gres: gres/cpu:0
                    submit_dir: /gpfs/work3/0/prjs1291/Hafeez_thesis/Can3Tok
                    submit_host: int6.local.snellius.surf.nl
                    task_pid: "1719495"
                    tasks_per_node: "1"
                    topology_addr: root.ibsw40.gcn113
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=9
                startedAt: "2026-01-29T13:25:40.447485Z"
                writerId: 02ivrsg817qm0iq0epdphdkvh7gpmm4u
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 71
                - 103
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: Can3Tok-Perceiver-VAE
batch_size:
    value: 128
batches_per_epoch:
    value: 4
dataset:
    value: SceneSplat-7K
epochs:
    value: 1000
eval_every:
    value: 50
failure_threshold:
    value: 1000
kl_weight:
    value: 1e-05
learning_rate:
    value: 0.0001
model_config:
    value: shapevae-256
num_gaussians:
    value: 40000
num_train_scenes:
    value: 500
num_val_scenes:
    value: 50
random_permute:
    value: false
random_rotation:
    value: true
train_scenes:
    value: 500
val_scenes:
    value: 50
